# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 61197f718ab2e3bfe6065f611c61f4c316678510


{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 61197f718ab2e3bfe6065f611c61f4c316678510

# 61197f718ab2e3bfe6065f611c61f4c316678510 1st_user
# cba2792ccac3292427d737f2d6580dc0215d032a Shurik_user
# 4f59d8a619e8ddb81fbfe134ee43c749bfc83416 Abu_user
{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
